# title: "Swarnabha Roy"
# email: swarnabha4399@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   A short bio about yourself. Enthusiastic developer with a passion for coding and problem-solving.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swarn4399.github.io" # the base hostname & protocol for your site
# twitter_username: yourusername
github_username:  swarn4399

# _config.yml
theme: minima

# Other configurations
markdown: kramdown

# # Custom CSS
# plugins:
#   - jekyll-remote-theme # add this line
# remote_theme: "pages-themes/minimal@v0.2.0"

include:
  - assets

# sass:
#   style: compressed

# Other configurations

# Site configuration
title: Swarnabha Roy
# description: Your site description
author: Swarnabha Roy
email: swarnabha4399@gmail.com
# twitter: yourusername
github: swarn4399
linkedin: swarnabharoy

