baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swarn4399.github.io" # the base hostname & protocol for your site
header_pages:
  - index.md
  - about-me.md
  - news.md
# twitter_username: yourusername
github_username:  swarn4399

# _config.yml
theme: minima

# Other configurations
markdown: kramdown

include:
  - assets

# Other configurations

# Site configuration
title: Swarnabha Roy
author: Swarnabha Roy
email: swarnabha4399@gmail.com
github: swarn4399
linkedin: swarnabharoy

